// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AccountForm: typeof import('./components/AccountForm.vue')['default']
    DealForm: typeof import('./components/DealForm.vue')['default']
    FormWrapper: typeof import('./components/FormWrapper.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Initializator: typeof import('./components/Initializator.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    MyButton: typeof import('./components/MyButton.vue')['default']
    MyFooter: typeof import('./components/MyFooter.vue')['default']
    MyHeader: typeof import('./components/MyHeader.vue')['default']
    MyInput: typeof import('./components/MyInput.vue')['default']
    PhoneInput: typeof import('./components/PhoneInput.vue')['default']
  }
}

export { }
